---
- name: Set default interface to public
  firewalld:
    interface: "{{ansible_default_ipv4.interface}}"
    zone: public
    permanent: true
    immediate: true
    state: enabled

- name: Enable openvpn service in public
  firewalld:
    zone: public
    service: openvpn
    state: enabled
    permanent: true

- name: Enable openvpn port in public
  firewalld:
    zone: public
    port: "{{ openvpn_port }}/{{ openvpn_protocol }}"
    state: enabled
    permanent: true

- name: Set tun0 to trusted
  firewalld:
    interface: tun0
    zone: trusted
    permanent: true
    immediate: true
    state: enabled

- name: Enable services in trusted
  firewalld:
    service: "{{ item }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - ssh
    - dns

- name: Enable ports in trusted zone
  firewalld:
    port: "{{ item }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - 53/tcp
    - 53/udp
    - 22/tcp

- name: Enable masquerate
  firewalld:
    zone: "{{ item }}"
    masquerade: yes
    state: enabled
    permanent: true
  with_items:
    - trusted
    - public

- name: Bounce firewalld
  service:
    name: firewalld
    state: restarted