---
- name: Enable IPv4 traffic forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Ensure firewalld is started
  service:
    name: firewalld
    state: started

- name: Set default interface to public
  firewalld:
    interface: "{{ansible_default_ipv4.interface}}"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Restart firewalld

- name: Enable openvpn port in public
  firewalld:
    zone: public
    port: "{{ openvpn_port }}/{{ openvpn_protocol }}"
    state: enabled
    permanent: true
  notify:
    - Restart firewalld

- name: Set tun0 to trusted
  firewalld:
    interface: tun0
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Restart firewalld

- name: Enable ports in trusted zone
  firewalld:
    port: "{{ item }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - 53/tcp
    - 53/udp
    - 22/tcp
  notify:
    - Restart firewalld

- name: Enable masquerade
  firewalld:
    zone: "{{ item }}"
    masquerade: yes
    state: enabled
    permanent: true
  with_items:
    - trusted
    - public
  notify:
    - Restart firewalld

