---
- name: Install EPEL
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: Remove non-required packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ unwanted_packages }}"

- name: Install required packages
  package:
    name: "{{ item }}"
  with_items: "{{ required_packages }}"

