---
- name: Restart openvpn
  systemd:
    state: restarted
    daemon_reload: yes
    name: openvpn

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted